public/auth.html
=> [feature/net-48] 로딩페이지 애니메이션 적용

public/components/main_cont.js, public/index.html, public/stylesheets/mainstyle/login-info.css, public/stylesheets/mainstyle/main_container.css
로그인 기능 UX 일부 추가 / 취향 버튼 부분 UI 추가
=> [feature/net-49] 로그인 기능 UX 일부 추가 / 취향 버튼 부분 추가

routes/api/auth/AuthService.js
=> [feature/net-54] message 보낼시 도메인을 항상 고정으로 설정

.idea/jsLibraryMappings.xml, .idea/takealook.iml, public/auth.html, public/components/axios/axios.js, public/components/elements/movies/MoviesElements.js, public/components/index/header.js, public/components/index/initialize.js, public/index.html, routes/api/ApiRouter.js, routes/api/member/MemberService.js, routes/api/movie/MovieRouter.js, routes/api/movie/MovieService.js, routes/api/movie/MovieStorage.js
=> [feature/net-55] 메인화면 기본 영화 정보 뿌리기

public/mylist.html, public/stylesheets/myliststyle/listheader.css, public/stylesheets/style.css
=> [feature/net-56]내 리스트 작업 수행

public/account.html, public/components/account/account.js, public/components/index/main_cont.js, public/index.html, public/stylesheets/mainstyle/intro_content.css, public/stylesheets/responsive.css
=> [feature/net-59] 회원가입 셀렉트박스 스크립트 적용

public/index.html, public/stylesheets/mainstyle/header.css, public/stylesheets/responsive.css
=> [feature/net-71] 검색바 기능 디자인 수정

public/myinformation.html, public/mylist.html, public/stylesheets/mainstyle/myinformation/myinfo_media.css, public/stylesheets/mainstyle/myinformation/myinformation.css, public/stylesheets/myliststyle/mycollection.css
=> [feature/net-64]내정보창 작업 완료하였습니다

public/components/index/header.js, public/components/index/headerBtnEvents.js, public/index.html, public/stylesheets/mainstyle/header.css, public/stylesheets/mainstyle/main_container.css, public/stylesheets/mainstyle/modal_cover.css, public/stylesheets/modal_loading.css, public/stylesheets/style.css
=> [feature/net-72] 검색바 스크립트 적용

public/components/elements/MoviesElements.js, public/components/index/main_cont.js, public/components/search/main_cont.js, public/index.html, public/search.html, public/stylesheets/account.css, public/stylesheets/mainstyle/login-info.css
=> [feature/net-81] 회원가입 및 검색 페이지 일부 UI/UX 개선

public/mylist.html, public/stylesheets/myliststyle/mycollection.css, public/stylesheets/myliststyle/reaction_call.css
=> [feature/net-82]내 리스트 반응형 작업

public/myinformation.html, public/stylesheets/mainstyle/myinformation/myinfo_media.css, public/stylesheets/mainstyle/myinformation/myinformation.css, public/stylesheets/myliststyle/mycollection.css
=> [feature/net-87]내 프로필 디자인 수수정 작업

public/myinformation.html, public/stylesheets/mainstyle/myinformation/myinfo_media.css, public/stylesheets/mainstyle/myinformation/myinformation.css
=> [feature/net-92]"내 프로필 작업 완료"

public/account.html, public/components/index/main_cont.js, public/index.html, public/stylesheets/mainstyle/fav_container.css, public/stylesheets/mainstyle/header.css, public/stylesheets/mainstyle/intro_content.css, public/stylesheets/mainstyle/main_container.css, public/stylesheets/mainstyle/modal_cover.css, public/stylesheets/responsive.css
=> [feature/net-90] 일부 UI 수정 작업 및 반응형 UI 개선

public/index.html, public/stylesheets/mainstyle/login-info.css, public/stylesheets/mainstyle/modal_cover.css, public/stylesheets/mainstyle/modal_select.css, public/stylesheets/style.css
일부 UI 수정 작업 및 내 리스트 페이지용 모달 틀 추가
=> [feature/net-99] 일부 UI 수정 작업 및 내 리스트 페이지용 모달 틀 추가

public/index.html, public/search.html
=> [feature/net-100] search.html 교체

public/index.html, public/stylesheets/mainstyle/modal_select.css
=> [feature/net-101] 내 리스트 셀렉트 모달 디자인 시안

public/components/info/image_select_modal.js, public/components/mylist/mylist.js, public/mylist.html, public/stylesheets/myliststyle/mycollection.css
=> [feature/net-112] 내 리스트 페이지 UI/UX 기능 추가

public/components/header/header.js, public/components/mylist/mylist.js, public/mylist.html, public/stylesheets/mainstyle/header.css, public/stylesheets/mainstyle/modal_select.css, public/stylesheets/myliststyle/mycollection.css
=> [feature/net-116] 내 리스트 셀렉트 모달 수정

public/mylist.html, public/stylesheets/myliststyle/mycollection.css, public/stylesheets/myliststyle/reaction_call.css
=> [feature/net-118] 내 리스트 반응형 UI 수정 작업

public/components/header/header.js, public/components/mylist/myListEvents.js, public/components/mylist/mylist.js, public/index.html, public/mylist.html, public/stylesheets/mainstyle/modal_cover.css, public/stylesheets/mainstyle/modal_select.css, public/stylesheets/mainstyle/myinformation/image_select_modal.css, public/stylesheets/myliststyle/mycollection.css, public/stylesheets/myliststyle/reaction_call.css
=> [feature/net-119] 영화 폴더 리스트 선택 모달 UI기능 수정

public/mylist.html, public/stylesheets/myliststyle/modal_select.css, public/stylesheets/style.css
=> [feature/net-125] 영화폴더 리스트 모달 UI수정 및 CSS파일 정리

public/components/index/main_cont.js, public/components/mylist/myListEvents.js, public/myinformation.html, public/stylesheets/mainstyle/fav_container.css, public/stylesheets/mainstyle/myinformation/myinfo_media.css, public/stylesheets/myliststyle/modal_select.css, public/stylesheets/myliststyle/mycollection.css, public/stylesheets/myliststyle/reaction_call.css, public/stylesheets/responsive.css
=> [feature/net-127] 전체 페이지 UI 개선 작업 및 페이지 점검

public/shared_list.html, public/stylesheets/mainstyle/shared_list.css, public/stylesheets/myliststyle/modal_select.css, public/stylesheets/style.css
일부 UI 수정 및 공유된 취향리스트 선택시 나오는 영화리스트 새 페이지 제작
=> [feature/net-134] 일부 UI 수정 및 공유된 취향리스트 선택시 나오는 영화리스트 새 페이지 제작

public/components/elements/favContElements.js, public/index.html, public/shared_list.html, public/stylesheets/mainstyle/shared_list.css, public/stylesheets/myliststyle/mycollection.css, public/stylesheets/responsive.css
=> [feature/net-138] 취향공유 리스트 페이지 및 일부 UI 수정 작업

public/mylist.html
=> [feature/net-143] 내 리스트 페이지 검색창 제거
